<?php

namespace app\admin\controller;

use think\Controller;

/**
 * 栏目管理
 * Class Category
 * @package app\admin\controller
 */
class Category extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Category();
    }

    //首页
    public function index()
    {
        return $this->fetch();
    }

    //添加栏目
    public function store()
    {
        if (request()->isPost()){
            //halt(input('post.'));
            $res = $this->db->store(input('post.'));
            if ($res['valid']){
               $this->success($res['msg'],'index');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        return $this->fetch();
    }
}
